---
- name: Configure Frontend Servers
  hosts: _frontend_dev_ujwal_final_project
  gather_facts: true
  become: true
  roles:
    - frontend
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300
    

- name: Configure Backend Servers
  hosts: _backend_dev_ujwal_final_project
  gather_facts: true
  become: true
  roles:
    - backend
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300